### ISSUE TITLE
Master issue

### ISSUE THREAD

**Issue by infwinston** [redteaming-arena/project-enigma#5]
Goals: 
- A website to host multiple redteam games 
- All games shared a common infrastructure. Can be easily configured by an YAML file 

Todo
- [x] database schema (MongoDB) @LVivona 
- [x] user API @LVivona 
- [x] Game/Session API: initiate a game session, play session, conclude session @terrianne-zhang
   - [x] create PR for code review @terrianne-zhang  
- [ ] Leaderboard API: refresh leaderboard for a game @aangelopoulos 
- [x] API <-> data schema review @infwinston 
- [ ] NoRefund design doc @shizhouxing @YihanWang617 
   - [x] prototype/demo
- [x] Judge API
- [x] Model API

Milestone
- [x] Support BadWords
- [ ] New UI to host many games

**Comment by infwinston** [comment]
11/19 action items
- [ ] integrate chat UI/backend
  - [ ] bad words
  - [ ] no funds 
  - [ ] LLM judge based game @jeffreysijuntan 
- [ ] cloud run for backend for auto-scaling/auto-recovering
- [ ] add Play button
- [ ] game history (win, loss, game title, ...)
- [ ] anonymous mode
- [ ] leaderboard as a service (cronjob)
